using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ResultGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class SourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext ctx)
    {
        var targetMethods = ctx.SyntaxProvider.ForAttributeWithMetadataName(
            "ResultGenerator.ReturnsResultAttribute",
            (node, _) => node is MethodDeclarationSyntax,
            (syntaxCtx, _) =>
            {
                return 0;
            });

        ctx.RegisterPostInitializationOutput(initCtx =>
        {
            initCtx.AddSource("uwu.g.cs", """
            /// <auto-generated/>

            using System;

            public static class S
            {
                public static void Hello() => Console.WriteLine("uwu");
            }
            """);
        });

        ctx.RegisterSourceOutput(targetMethods, (sourceCtx, method) =>
        {
            
        });
    }
}
