using Microsoft.CodeAnalysis.Testing;
using VerifyCS = ResultGenerator.Tests.Verifiers.CSharpIncrementalGeneratorVerifier<ResultGenerator.SourceGenerator>;

namespace ResultGenerator.Tests;

public class Tests
{
    private const string Header = """
    using System;
    using ResultGenerator;

    namespace ResultGenerator
    {
        [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
        public sealed class ReturnsResultAttribute : Attribute
        {
            public ReturnsResultAttribute() {}
            
            public ReturnsResultAttribute(string typeName) {}
        }
    }


    """;

    [Fact]
    public async Task GeneratesResultFromInferredName()
    {
        var code = Header + """
        public sealed class PersonService
        {
            [ReturnsResult]
            [result: Ok, NotFound]
            public void GetPerson() =>
                throw new NotImplementedException();
        }
        """;

        var expected = """
        /// <auto-generated/>

        using System.Diagnostics.CodeAnalysis;

        #nullable enable

        public readonly struct GetPersonResult
        {
            private readonly int _flag;
            
            // Variant Ok has no data.
            // Variant NotFound has no data.
            
            private GetPersonResult(int flag)
            {
                this._flag = flag;
            }

            public static GetPersonResult Ok() => new(1);
            public static GetPersonResult NotFound() => new(2);
            
            public bool IsOk => this._flag == 1;
            public bool IsNotFound => this._flag == 2;
            
            // Variant Ok has no data to try get.
            // Variant NotFound has no data to try get.
        }

        """;

        await VerifyCS.VerifyGeneratorAsync(
            code,
            ("GetPersonResult.g.cs", expected));
    }

    [Fact]
    public async Task GeneratesResultFromExplicitName()
    {
        var code = Header + """
        public sealed class PersonService
        {
            [ReturnsResult("GetPersonRes")]
            [result: Ok, NotFound]
            public void GetPerson() =>
                throw new NotImplementedException();
        }
        """;

        var expected = """
        /// <auto-generated/>

        using System.Diagnostics.CodeAnalysis;

        #nullable enable

        public readonly struct GetPersonRes
        {
            private readonly int _flag;
            
            // Variant Ok has no data.
            // Variant NotFound has no data.
            
            private GetPersonRes(int flag)
            {
                this._flag = flag;
            }

            public static GetPersonRes Ok() => new(1);
            public static GetPersonRes NotFound() => new(2);
            
            public bool IsOk => this._flag == 1;
            public bool IsNotFound => this._flag == 2;
            
            // Variant Ok has no data to try get.
            // Variant NotFound has no data to try get.
        }

        """;

        await VerifyCS.VerifyGeneratorAsync(
            code,
            ("GetPersonRes.g.cs", expected));
    }
}
